# Generated by Django 3.0.7 on 2020-09-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('profile_picture', models.ImageField(upload_to='windowshoppi_post_picture')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
